package gui;


import core.clusterObject;
import core.clusterXml;
import core.documentObject;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.xml.parsers.ParserConfigurationException;
import org.carrot2.core.Cluster;
import org.xml.sax.SAXException;

/**
 * @author Sean Treacy
 * @author Aaron Hastings
 */
public class TwitterVisGui extends javax.swing.JFrame {

    /**
     * Creates new form TwitterVisGui
     */
    public TwitterVisGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clusterScrollPane = new javax.swing.JScrollPane();
        clusterTextArea = new javax.swing.JTextArea();
        fileUrlTextField = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        runButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        clusterTextArea.setColumns(20);
        clusterTextArea.setRows(5);
        clusterScrollPane.setViewportView(clusterTextArea);

        browseButton.setText("Browse...");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        runButton.setText("Run");
        runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clusterScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fileUrlTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(browseButton)
                        .addGap(18, 18, 18)
                        .addComponent(runButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileUrlTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseButton)
                    .addComponent(runButton))
                .addGap(18, 18, 18)
                .addComponent(clusterScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        try {
            attach();
        } catch (IOException ex) {
            Logger.getLogger(TwitterVisGui.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(TwitterVisGui.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SAXException ex) {
            Logger.getLogger(TwitterVisGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_browseButtonActionPerformed

    public void attach() throws IOException, ParserConfigurationException, SAXException {
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(null);
        File f = fc.getSelectedFile();
        fileUrlTextField.setText(f.getAbsolutePath());
    }

    private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButtonActionPerformed
        clusterXml cluster = new clusterXml();
        ArrayList <clusterObject> clusterObjects = new ArrayList<clusterObject>();
        
        String fileUrl = fileUrlTextField.getText();
        try {
            clusterObjects = cluster.clusterXmlFile(fileUrl);
            
            for (clusterObject c : clusterObjects)
            {
                clusterTextArea.append("\n ==== Cluster Topic: " + c.getTopic() + " ==== ");
                clusterTextArea.append("\n ==== Number of documents in cluster: " + c.getNumDocuments() + " ==== \n");
                for (documentObject d : c.documents)
                {
                    clusterTextArea.append(" -- Document -- \n" + d.getSnippet() + "\n\n");
                }
            }
        } catch (IOException | ParserConfigurationException | SAXException e) {
            e.printStackTrace(System.out);
        }
    }//GEN-LAST:event_runButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;


}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TwitterVisGui.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TwitterVisGui.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TwitterVisGui.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TwitterVisGui.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TwitterVisGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseButton;
    private javax.swing.JScrollPane clusterScrollPane;
    private javax.swing.JTextArea clusterTextArea;
    private javax.swing.JTextField fileUrlTextField;
    private javax.swing.JButton runButton;
    // End of variables declaration//GEN-END:variables
}
