package gui;

import core.clusterObject;
import core.clusterXml;
import core.documentObject;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.xml.parsers.ParserConfigurationException;
import org.xml.sax.SAXException;
/**
 * @author Aaron Hastings
 * @author Sean Treacy
 */
public class TwitterVisGui extends javax.swing.JFrame {

    /**
     * Creates new form TwitterVisGui
     */
    public TwitterVisGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileUrlTextField = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        runButton = new javax.swing.JButton();
        algoComboBox = new javax.swing.JComboBox();
        algoLabel = new javax.swing.JLabel();
        searchQueryTextField = new javax.swing.JTextField();
        clusterTabbedPane = new javax.swing.JTabbedPane();
        rawOutputScrollPane = new javax.swing.JScrollPane();
        rawOutputTextArea = new javax.swing.JTextArea();
        graphScrollPane = new javax.swing.JScrollPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileUrlTextField.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        fileUrlTextField.setText("Choose a file by clicking \"Browse...\"");

        browseButton.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        browseButton.setText("Browse...");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        runButton.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        runButton.setText("    Run    ");
        runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonActionPerformed(evt);
            }
        });

        algoComboBox.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        algoComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lingo", "STC" }));

        algoLabel.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        algoLabel.setText("Algorithm");

        searchQueryTextField.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        searchQueryTextField.setText("Enter a search query...");
        searchQueryTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchQueryTextFieldMouseClicked(evt);
            }
        });
        searchQueryTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchQueryTextFieldFocusLost(evt);
            }
        });

        clusterTabbedPane.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        rawOutputTextArea.setEditable(false);
        rawOutputTextArea.setColumns(20);
        rawOutputTextArea.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        rawOutputTextArea.setLineWrap(true);
        rawOutputTextArea.setRows(5);
        rawOutputTextArea.setWrapStyleWord(true);
        rawOutputScrollPane.setViewportView(rawOutputTextArea);
        javax.swing.text.DefaultCaret caret = (javax.swing.text.DefaultCaret) rawOutputTextArea.getCaret();
        caret.setUpdatePolicy(javax.swing.text.DefaultCaret.NEVER_UPDATE);

        clusterTabbedPane.addTab("Raw Output", rawOutputScrollPane);
        clusterTabbedPane.addTab("Graph", graphScrollPane);

        fileMenu.setText("File");
        fileMenu.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        exitMenuItem.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText("Help");
        helpMenu.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        aboutMenuItem.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        aboutMenuItem.setText("About TweetVis");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clusterTabbedPane)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fileUrlTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(browseButton))
                            .addComponent(searchQueryTextField))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(algoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(runButton))
                            .addComponent(algoLabel))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fileUrlTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(browseButton))
                    .addComponent(algoLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchQueryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(algoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(runButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clusterTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        try {
            attach();
        } catch (IOException ex) {
            Logger.getLogger(TwitterVisGui.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(TwitterVisGui.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SAXException ex) {
            Logger.getLogger(TwitterVisGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_browseButtonActionPerformed

    public void attach() throws IOException, ParserConfigurationException, SAXException {
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(null);
        File f = fc.getSelectedFile();
        fileUrlTextField.setText(f.getAbsolutePath());
    }

    private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButtonActionPerformed
        rawOutputTextArea.setText("");
        String algo = algoComboBox.getSelectedItem().toString();
        clusterXml cluster = new clusterXml(algo);
        ArrayList <clusterObject> clusterObjects = new ArrayList<clusterObject>();
        String fileUrl = fileUrlTextField.getText();

        try {
            clusterObjects = cluster.clusterXmlFile(fileUrl);
            int numClusters= clusterObjects.size();
            rawOutputTextArea.append("\n ==== Number Clusters: " + numClusters + " ==== ");
            rawOutputTextArea.append("\n*******************************************");
             rawOutputTextArea.append("\n");
            
            for (clusterObject c : clusterObjects)
            {
                rawOutputTextArea.append("\n ==== Cluster Topic: " + c.getTopic() + " ==== ");
                rawOutputTextArea.append("\n ==== Number of documents in cluster: " + c.getNumDocuments() + " ==== \n");
                for (documentObject d : c.documents)
                {
                    rawOutputTextArea.append(" -- Document -- \n" + d.getSnippet() + "\n\n");
                }
            }
        } catch (IOException ioe) {
            ioe.printStackTrace(System.out);
        } catch (ParserConfigurationException pce) {
            pce.printStackTrace(System.out);
        } catch (SAXException saxe) {
            saxe.printStackTrace(System.out);
        }
    }//GEN-LAST:event_runButtonActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        AboutDialog aboutDialog = new AboutDialog(null, true);
        aboutDialog.setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void searchQueryTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchQueryTextFieldMouseClicked
        if (searchQueryTextField.getText().equals("Enter a search query..."))
            searchQueryTextField.setText("");
    }//GEN-LAST:event_searchQueryTextFieldMouseClicked

    private void searchQueryTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchQueryTextFieldFocusLost
        if (searchQueryTextField.getText().equals(""))
            searchQueryTextField.setText("Enter a search query...");
    }//GEN-LAST:event_searchQueryTextFieldFocusLost
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;


}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TwitterVisGui.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TwitterVisGui.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TwitterVisGui.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TwitterVisGui.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TwitterVisGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JComboBox algoComboBox;
    private javax.swing.JLabel algoLabel;
    private javax.swing.JButton browseButton;
    private javax.swing.JTabbedPane clusterTabbedPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JTextField fileUrlTextField;
    private javax.swing.JScrollPane graphScrollPane;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JScrollPane rawOutputScrollPane;
    private javax.swing.JTextArea rawOutputTextArea;
    private javax.swing.JButton runButton;
    private javax.swing.JTextField searchQueryTextField;
    // End of variables declaration//GEN-END:variables
}
