package gui;


import core.clusterObject;
import core.clusterXml;
import core.documentObject;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.xml.parsers.ParserConfigurationException;
import org.carrot2.core.Cluster;
import org.xml.sax.SAXException;
/**
 * @author Sean Treacy
 * @author Aaron Hastings
 */
public class TwitterVisGui extends javax.swing.JFrame {

    /**
     * Creates new form TwitterVisGui
     */
    public TwitterVisGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clusterScrollPane = new javax.swing.JScrollPane();
        clusterTextArea = new javax.swing.JTextArea();
        fileUrlTextField = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        runButton = new javax.swing.JButton();
        algoComboBox = new javax.swing.JComboBox();
        algoLabel = new javax.swing.JLabel();
        searchQueryTextField = new javax.swing.JTextField();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        aboutMenu = new javax.swing.JMenu();
        aboutTwitterVisMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        clusterTextArea.setColumns(20);
        clusterTextArea.setRows(5);
        clusterScrollPane.setViewportView(clusterTextArea);

        fileUrlTextField.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        fileUrlTextField.setText("Choose a file by clicking \"Browse...\"");
        fileUrlTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileUrlTextFieldActionPerformed(evt);
            }
        });

        browseButton.setText("Browse...");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        runButton.setText("    Run    ");
        runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonActionPerformed(evt);
            }
        });

        algoComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lingo", "STC" }));

        algoLabel.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        algoLabel.setText("Algorithm");

        searchQueryTextField.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        searchQueryTextField.setText("Enter a search query...");
        searchQueryTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchQueryTextFieldMouseClicked(evt);
            }
        });
        searchQueryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchQueryTextFieldActionPerformed(evt);
            }
        });
        searchQueryTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchQueryTextFieldFocusLost(evt);
            }
        });

        fileMenu.setText("File");

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        aboutMenu.setText("About");
        aboutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuActionPerformed(evt);
            }
        });

        aboutTwitterVisMenuItem.setText("About TwitterVis");
        aboutTwitterVisMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutTwitterVisMenuItemActionPerformed(evt);
            }
        });
        aboutMenu.add(aboutTwitterVisMenuItem);

        menuBar.add(aboutMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fileUrlTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(browseButton))
                            .addComponent(searchQueryTextField))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(algoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(algoLabel))
                        .addGap(6, 6, 6)
                        .addComponent(runButton))
                    .addComponent(clusterScrollPane))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fileUrlTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(browseButton))
                    .addComponent(algoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchQueryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(algoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(runButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clusterScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        try {
            attach();
        } catch (IOException ex) {
            Logger.getLogger(TwitterVisGui.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(TwitterVisGui.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SAXException ex) {
            Logger.getLogger(TwitterVisGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_browseButtonActionPerformed

    public void attach() throws IOException, ParserConfigurationException, SAXException {
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(null);
        File f = fc.getSelectedFile();
        fileUrlTextField.setText(f.getAbsolutePath());
    }

    private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButtonActionPerformed
        clusterTextArea.setText("");
        String algo = algoComboBox.getSelectedItem().toString();
        clusterXml cluster = new clusterXml(algo);
        ArrayList <clusterObject> clusterObjects = new ArrayList<clusterObject>();
        
        String fileUrl = fileUrlTextField.getText();

        try {
            clusterObjects = cluster.clusterXmlFile(fileUrl);
            int numClusters= clusterObjects.size();
            clusterTextArea.append("\n ==== Number Clusters: " + numClusters + " ==== ");
            clusterTextArea.append("\n*******************************************");
             clusterTextArea.append("\n");
            
            for (clusterObject c : clusterObjects)
            {
                clusterTextArea.append("\n ==== Cluster Topic: " + c.getTopic() + " ==== ");
                clusterTextArea.append("\n ==== Number of documents in cluster: " + c.getNumDocuments() + " ==== \n");
                for (documentObject d : c.documents)
                {
                    clusterTextArea.append(" -- Document -- \n" + d.getSnippet() + "\n\n");
                }
            }
        } catch (IOException ioe) {
            ioe.printStackTrace(System.out);
        } catch (ParserConfigurationException pce) {
            pce.printStackTrace(System.out);
        } catch (SAXException saxe) {
            saxe.printStackTrace(System.out);
        }
    }//GEN-LAST:event_runButtonActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void aboutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutMenuActionPerformed

    private void aboutTwitterVisMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutTwitterVisMenuItemActionPerformed
//        JPanel aboutPanel = new JPanel();
//        aboutPanel.setSize(500, 500);
//        aboutPanel.setVisible(true);
        
        JDialog aboutDialog = new JDialog();
        aboutDialog.setSize(500, 500);
        aboutDialog.setVisible(true);
    }//GEN-LAST:event_aboutTwitterVisMenuItemActionPerformed

    private void fileUrlTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileUrlTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileUrlTextFieldActionPerformed

    private void searchQueryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchQueryTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchQueryTextFieldActionPerformed

    private void searchQueryTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchQueryTextFieldMouseClicked
        if (searchQueryTextField.getText().equals("Enter a search query..."))
            searchQueryTextField.setText("");
    }//GEN-LAST:event_searchQueryTextFieldMouseClicked

    private void searchQueryTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchQueryTextFieldFocusLost
        if (searchQueryTextField.getText().equals(""))
            searchQueryTextField.setText("Enter a search query...");
    }//GEN-LAST:event_searchQueryTextFieldFocusLost
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;


}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TwitterVisGui.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TwitterVisGui.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TwitterVisGui.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TwitterVisGui.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TwitterVisGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu aboutMenu;
    private javax.swing.JMenuItem aboutTwitterVisMenuItem;
    private javax.swing.JComboBox algoComboBox;
    private javax.swing.JLabel algoLabel;
    private javax.swing.JButton browseButton;
    private javax.swing.JScrollPane clusterScrollPane;
    private javax.swing.JTextArea clusterTextArea;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JTextField fileUrlTextField;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JButton runButton;
    private javax.swing.JTextField searchQueryTextField;
    // End of variables declaration//GEN-END:variables
}
